package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Company;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Mar 31 13:21:49 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Mar 31 13:21:49 EEST 2021
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Mar 31 13:21:49 EEST 2021
     */
    Company selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Mar 31 13:21:49 EEST 2021
     */
    List<Company> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Mar 31 13:21:49 EEST 2021
     */
    int updateByPrimaryKey(Company record);
}